#!/bin/sh
set -eu

echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check

echo '+cargo clippy --all-targets --all-features --locked -- -D warnings'
cargo clippy --all-targets --all-features --locked -- -D warnings
